[package]
name = "arbitrage"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdlib"]

[dependencies]
anchor-lang = "0.27.0"
anchor-spl = "0.27.0"
solana-program = "1.14"
mango-v4 = { git = "https://github.com/blockworks-foundation/mango-v4", features = ["client"] } 